# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - physicsexpirements

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bca2f15d0f5a415b9c0ca2aba01f1bf8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8f7f431b66d641208b01989d37ce116d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_bca2f15d0f5a415b9c0ca2aba01f1bf8 }}/junepark678/ploosh-docs:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'physicsexpirements'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f31a714a87c49ee857c48b913e3d95a }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_bca2f15d0f5a415b9c0ca2aba01f1bf8 }}/junepark678/ploosh-docs:${{ github.sha }}'